Loading required package: maps

Attaching package: ‘reshape’

The following object is masked from ‘package:Matrix’:

    expand

Loading required package: nloptr
Loading required package: GenSA
Loading required package: subplex
Loading required package: TreeSim
Loading required package: geiger
Loading required package: deSolve
Found more than one class "atomicVector" in cache; using the first, from namespace 'Matrix'
Also defined by ‘Rmpfr’
Found more than one class "atomicVector" in cache; using the first, from namespace 'Matrix'
Also defined by ‘Rmpfr’
Found more than one class "atomicVector" in cache; using the first, from namespace 'Matrix'
Also defined by ‘Rmpfr’
Found more than one class "atomicVector" in cache; using the first, from namespace 'Matrix'
Also defined by ‘Rmpfr’
Found more than one class "atomicVector" in cache; using the first, from namespace 'Matrix'
Also defined by ‘Rmpfr’
Found more than one class "atomicVector" in cache; using the first, from namespace 'Matrix'
Also defined by ‘Rmpfr’
Found more than one class "atomicVector" in cache; using the first, from namespace 'Matrix'
Also defined by ‘Rmpfr’
Found more than one class "atomicVector" in cache; using the first, from namespace 'Matrix'
Also defined by ‘Rmpfr’
Found more than one class "atomicVector" in cache; using the first, from namespace 'Matrix'
Also defined by ‘Rmpfr’
Found more than one class "atomicVector" in cache; using the first, from namespace 'Matrix'
Also defined by ‘Rmpfr’
Found more than one class "atomicVector" in cache; using the first, from namespace 'Matrix'
Also defined by ‘Rmpfr’
Found more than one class "atomicVector" in cache; using the first, from namespace 'Matrix'
Also defined by ‘Rmpfr’
── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.5     ✔ dplyr   1.0.7
✔ tidyr   1.1.4     ✔ stringr 1.4.0
✔ readr   2.0.2     ✔ forcats 0.5.1
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ tidyr::expand() masks reshape::expand(), Matrix::expand()
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ purrr::map()    masks maps::map()
✖ tidyr::pack()   masks Matrix::pack()
✖ dplyr::rename() masks reshape::rename()
✖ tidyr::unpack() masks Matrix::unpack()
Rows: 13801 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (7): ID, Language_ID, Parameter_ID, Value, Code_ID, Source, Examples
lgl (1): Comment

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Working on tree 82 
 0  1 
58  3 
Fitting GB020 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	58	3	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB020 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	58	3	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
59  2 
Fitting GB021 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	59	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB021 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	59	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 45 15 
Fitting GB022 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	45	15	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB022 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	45	15	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
57  4 
Fitting GB023 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	57	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB023 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	57	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
31 22  8 
Fitting GB026 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	22	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB026 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	22	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
26 18 17 
Fitting GB027 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	18	17	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB027 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	18	17	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 42 16 
Fitting GB028 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	42	16	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB028 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	42	16	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 57  1 
Fitting GB030 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	57	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB030 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	57	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4 54  3 
Fitting GB031 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	54	3	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB031 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	54	3	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 5 37 19 
Fitting GB035 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	37	19	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB035 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	37	19	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 5 54  2 
Fitting GB037 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	54	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB037 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	54	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 43 15 
Fitting GB039 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	43	15	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB039 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	43	15	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 7 53  1 
Fitting GB041 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	53	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB041 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	53	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
60  1 
Fitting GB042 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB042 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
60  1 
Fitting GB043 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB043 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 15 45 
Fitting GB044 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	15	45	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB044 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	15	45	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
29  5 27 
Fitting GB046 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	5	27	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB046 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	5	27	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
19  3 39 
Fitting GB047 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	3	39	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB047 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	3	39	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
23  6 32 
Fitting GB048 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	6	32	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB048 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	6	32	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
20  5 36 
Fitting GB049 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	5	36	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB049 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	5	36	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 5 39 17 
Fitting GB057 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	39	17	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB057 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	39	17	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4 48  9 
Fitting GB059 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	48	9	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB059 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	48	9	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 6 41 14 
Fitting GB068 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	41	14	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB068 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	41	14	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 6 46  9 
Fitting GB069 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	46	9	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB069 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	46	9	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
 2 59 
Fitting GB070 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	2	59	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB070 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	2	59	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1  2 58 
Fitting GB071 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	2	58	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB071 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	2	58	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
 2 59 
Fitting GB072 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	2	59	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB072 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	2	59	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 2  1 58 
Fitting GB073 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	1	58	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB073 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	1	58	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 57  1 
Fitting GB074 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	57	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB074 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	57	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4  1 56 
Fitting GB075 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	1	56	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB075 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	1	56	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
60  1 
Fitting GB079 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB079 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
 1 60 
Fitting GB080 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	1	60	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB080 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	1	60	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1  9 51 
Fitting GB082 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	9	51	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB082 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	9	51	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
 3 58 
Fitting GB083 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	3	58	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB083 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	3	58	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 28 30 
Fitting GB084 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	28	30	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB084 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	28	30	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 14 44 
Fitting GB086 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	14	44	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB086 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	14	44	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
23 38 
Fitting GB089 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	23	38	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB089 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	23	38	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
23 38 
Fitting GB091 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	23	38	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB091 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	23	38	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 58  2 
Fitting GB103 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	58	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB103 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	58	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 6 50  5 
Fitting GB105 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	50	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB105 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	50	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 16 42 
Fitting GB107 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	16	42	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB107 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	16	42	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4 48  9 
Fitting GB108 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	48	9	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB108 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	48	9	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
14 46  1 
Fitting GB110 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	46	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB110 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	46	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 9 30 22 
Fitting GB111 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	30	22	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB111 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	30	22	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
10  1 50 
Fitting GB113 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	1	50	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB113 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	1	50	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
14 22 25 
Fitting GB114 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	22	25	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB114 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	22	25	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
12 10 39 
Fitting GB115 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	10	39	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB115 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	10	39	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
10  5 46 
Fitting GB117 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	5	46	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB117 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	5	46	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
23 30  8 
Fitting GB118 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	30	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB118 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	30	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4 20 37 
Fitting GB119 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	20	37	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB119 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	20	37	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4 16 41 
Fitting GB120 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	16	41	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB120 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	16	41	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 29 29 
Fitting GB121 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	29	29	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB121 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	29	29	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
20 33  8 
Fitting GB122 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	33	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB122 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	33	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
32  6 23 
Fitting GB123 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	6	23	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB123 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	6	23	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
19 12 30 
Fitting GB126 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	12	30	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB126 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	12	30	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
36 23  2 
Fitting GB127 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	23	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB127 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	23	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
57  4 
Fitting GB132 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	57	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB132 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	57	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
 1 60 
Fitting GB133 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	1	60	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB133 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	1	60	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
14  3 44 
Fitting GB134 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	3	44	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB134 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	3	44	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
22  6 33 
Fitting GB135 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	6	33	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB135 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	6	33	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
19 23 19 
Fitting GB136 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	23	19	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB136 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	23	19	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 2 15 44 
Fitting GB137 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	15	44	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB137 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	15	44	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4 55  2 
Fitting GB138 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	55	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB138 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	55	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 9 17 35 
Fitting GB139 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	17	35	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB139 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	17	35	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
11 43  7 
Fitting GB140 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	43	7	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB140 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	43	7	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
37 15  9 
Fitting GB146 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	15	9	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB146 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	15	9	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 2  7 52 
Fitting GB147 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	7	52	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB147 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	7	52	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 8  4 49 
Fitting GB150 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	4	49	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB150 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	4	49	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 59  1 
Fitting GB151 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	59	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB151 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	59	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 7  9 45 
Fitting GB152 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	9	45	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB152 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	9	45	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4  1 56 
Fitting GB155 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	1	56	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB155 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	1	56	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 2 58  1 
Fitting GB156 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	58	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB156 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	58	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
20 37  4 
Fitting GB158 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	37	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB158 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	37	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
20 35  6 
Fitting GB159 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	35	6	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB159 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	35	6	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
21 10 30 
Fitting GB160 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	10	30	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB160 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	10	30	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
60  1 
Fitting GB166 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB166 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4 55  2 
Fitting GB167 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	55	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB167 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	55	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 7 49  5 
Fitting GB184 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	49	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB184 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	49	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
20 29 12 
Fitting GB185 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	29	12	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB185 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	29	12	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
15  5 41 
Fitting GB187 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	5	41	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB187 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	5	41	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
16 40  5 
Fitting GB188 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	40	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB188 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	40	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 57  1 
Fitting GB196 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	57	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB196 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	57	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 57  1 
Fitting GB197 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	57	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB197 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	57	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
32  5 24 
Fitting GB204 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	5	24	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB204 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	5	24	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
19 38  4 
Fitting GB250 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	38	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB250 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	38	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
22  9 30 
Fitting GB252 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	9	30	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB252 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	9	30	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
22 20 19 
Fitting GB253 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	20	19	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB253 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	20	19	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
18 20 23 
Fitting GB254 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	20	23	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB254 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	20	23	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
25 26 10 
Fitting GB256 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	26	10	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB256 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	26	10	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
10 41 10 
Fitting GB257 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	41	10	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB257 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	41	10	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 5  7 49 
Fitting GB263 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	7	49	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB263 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	7	49	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 6 52  3 
Fitting GB264 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	52	3	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB264 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	52	3	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
11 49  1 
Fitting GB265 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	49	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB265 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	49	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
12 10 39 
Fitting GB266 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	10	39	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB266 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	10	39	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 9 36 16 
Fitting GB273 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	36	16	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB273 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	36	16	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
15 33 13 
Fitting GB275 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	33	13	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB275 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	33	13	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
14 43  4 
Fitting GB276 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	43	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB276 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	43	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 6 54  1 
Fitting GB285 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	54	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB285 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	54	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 5 51  5 
Fitting GB286 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	51	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB286 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	51	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
19 28 14 
Fitting GB296 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	28	14	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB296 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	28	14	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4 56  1 
Fitting GB297 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	56	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB297 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	56	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 2 46 13 
Fitting GB298 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	46	13	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB298 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	46	13	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 5 40 16 
Fitting GB299 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	40	16	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB299 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	40	16	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
44 10  7 
Fitting GB301 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	10	7	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB301 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	10	7	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 59  1 
Fitting GB302 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	59	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB302 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	59	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
19  6 36 
Fitting GB304 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	6	36	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB304 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	6	36	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
10  2 49 
Fitting GB305 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	2	49	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB305 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	2	49	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
26 31  4 
Fitting GB306 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	31	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB306 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	31	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4 34 23 
Fitting GB309 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	34	23	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB309 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	34	23	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
 2 59 
Fitting GB312 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	2	59	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB312 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	2	59	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 5 48  8 
Fitting GB313 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	48	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB313 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	48	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
60  1 
Fitting GB316 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB316 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
60  1 
Fitting GB318 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB318 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 5 44 12 
Fitting GB322 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	44	12	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB322 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	44	12	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 6 40 15 
Fitting GB323 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	40	15	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB323 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	40	15	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
16 24 21 
Fitting GB324 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	24	21	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB324 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	24	21	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
19 30 12 
Fitting GB325 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	30	12	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB325 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	30	12	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
21  5 35 
Fitting GB326 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	5	35	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB326 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	5	35	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 8 44  9 
Fitting GB327 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	44	9	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB327 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	44	9	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 8  2 51 
Fitting GB328 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	2	51	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB328 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	2	51	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
19 37  5 
Fitting GB329 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	37	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB329 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	37	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
15 45  1 
Fitting GB330 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	45	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB330 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	45	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
10  1 50 
Fitting GB333 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	1	50	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB333 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	1	50	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 6 50  5 
Fitting GB400 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	50	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB400 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	50	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
46 10  5 
Fitting GB401 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	10	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB401 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	10	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
20 37  4 
Fitting GB403 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	37	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB403 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	37	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
 2 59 
Fitting GB408 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	2	59	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB408 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	2	59	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 5 55  1 
Fitting GB409 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	55	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB409 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	55	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 5 24 32 
Fitting GB410 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	24	32	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB410 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	24	32	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 40 18 
Fitting GB415 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	40	18	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB415 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	40	18	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
26 29  6 
Fitting GB421 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	29	6	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB421 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	29	6	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
28 25  8 
Fitting GB422 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	25	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB422 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	25	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
60  1 
Fitting GB431 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB431 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	60	1	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
11 50 
Fitting GB432 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	11	50	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB432 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	11	50	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 16 44 
Fitting GB433 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	16	44	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB433 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	16	44	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 47 11 
Fitting GB519 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	47	11	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB519 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	47	11	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 58  2 
Fitting GB520 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	58	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB520 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	58	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 56  4 
Fitting GB521 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	56	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB521 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	56	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
10  2 49 
Fitting GB522 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	2	49	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting GB522 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	2	49	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 2 28 31 
Fitting TE003 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	28	31	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE003 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	28	31	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 2 51  8 
Fitting TE004 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	51	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE004 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	51	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
11 39 11 
Fitting TE005 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	39	11	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE005 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	39	11	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
16 34 11 
Fitting TE006 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	34	11	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE006 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	34	11	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4 49  8 
Fitting TE007 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	49	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE007 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	49	8	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 12 48 
Fitting TE008 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	12	48	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE008 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	12	48	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 4 17 40 
Fitting TE018 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	17	40	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE018 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	17	40	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 15 43 
Fitting TE019 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	15	43	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE019 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	15	43	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 6 33 22 
Fitting TE027 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	33	22	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE027 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	33	22	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 16 44 
Fitting TE031 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	16	44	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE031 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	16	44	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 25 35 
Fitting TE037 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	25	35	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE037 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	25	35	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 18 42 
Fitting TE038 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	18	42	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE038 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	18	42	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 20 38 
Fitting TE039 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	20	38	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE039 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	20	38	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 6 53  2 
Fitting TE050 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	53	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE050 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	53	2	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 5 26 30 
Fitting TE052 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	26	30	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE052 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	26	30	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 3 23 35 
Fitting TE053 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	23	35	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE053 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	23	35	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
16  6 39 
Fitting TE054 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	6	39	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE054 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	6	39	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 8 46  7 
Fitting TE059 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	46	7	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE059 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	46	7	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
25 36 
Fitting TE066 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	25	36	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE066 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	25	36	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 2 55  4 
Fitting TE078 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	55	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TE078 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	55	4	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 5  3 53 
Fitting TS001 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	3	53	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TS001 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	3	53	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 7 41 13 
Fitting TS002 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	41	13	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TS002 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	41	13	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1  1 59 
Fitting TS003 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	1	59	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TS003 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	1	59	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1  1 59 
Fitting TS005 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	1	59	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TS005 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	1	59	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 17 43 
Fitting TS006 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	17	43	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TS006 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	17	43	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 2  1 58 
Fitting TS007 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	1	58	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TS007 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	1	58	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
30  8 23 
Fitting TS009 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	8	23	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TS009 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	8	23	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
32 19 10 
Fitting TS010 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	19	10	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TS010 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	19	10	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 6 50  5 
Fitting TS079 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	50	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TS079 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	50	5	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 6 31 24 
Fitting TS080 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	31	24	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TS080 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	31	24	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 0  1 
 1 60 
Fitting TS086 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	1	60	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TS086 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	1	60	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
 ?  0  1 
 1 48 12 
Fitting TS088 onto tree 82 using ER
State distribution in data:
States:	0	1	
Counts:	48	12	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
Fitting TS088 onto tree 82 using ARD
State distribution in data:
States:	0	1	
Counts:	48	12	
Initializing... 
Finished. Beginning thorough search... 
Finished. Inferring ancestral states using marginal reconstruction. 
