Loading required package: MASS
Loading required package: mvtnorm
Loading required package: maps
Loading required package: Matrix

Attaching package: ‘Matrix’

The following object is masked from ‘package:reshape’:

    expand

Loading required package: subplex
Loading required package: TreeSim
Loading required package: geiger
Loading required package: deSolve

Attaching package: ‘dplyr’

The following object is masked from ‘package:reshape’:

    rename

The following object is masked from ‘package:MASS’:

    select

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

── Attaching packages ─────────────────────────────────────── tidyverse 1.3.1 ──
✔ ggplot2 3.3.5     ✔ purrr   0.3.4
✔ tibble  3.1.5     ✔ stringr 1.4.0
✔ tidyr   1.1.4     ✔ forcats 0.5.1
✔ readr   2.0.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ tidyr::expand() masks Matrix::expand(), reshape::expand()
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
✖ purrr::map()    masks maps::map()
✖ tidyr::pack()   masks Matrix::pack()
✖ dplyr::rename() masks reshape::rename()
✖ dplyr::select() masks MASS::select()
✖ tidyr::unpack() masks Matrix::unpack()
trying URL 'https://raw.githubusercontent.com/cldf-datasets/hueblerstability/main/cldf/values.csv'
Content type 'text/plain; charset=utf-8' length 1026634 bytes (1002 KB)
==================================================
downloaded 1002 KB

Rows: 13801 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (7): ID, Language_ID, Parameter_ID, Value, Code_ID, Source, Examples
lgl (1): Comment

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
removing GB036 -- all zero
removing GB038 -- all zero
removing GB051 -- all zero
removing GB052 -- all zero
removing GB053 -- all zero
removing GB054 -- all zero
removing GB058 -- all zero
removing GB081 -- all zero
removing GB090 -- all zero
removing GB092 -- all zero
removing GB093 -- all zero
removing GB094 -- all zero
removing GB095 -- all zero
removing GB096 -- all zero
removing GB098 -- all zero
removing GB099 -- all zero
removing GB104 -- all zero
removing GB109 -- all zero
removing GB116 -- all zero
removing GB124 -- all zero
removing GB129 -- all zero
removing GB131 -- all zero
removing GB148 -- all zero
removing GB149 -- all zero
removing GB165 -- all zero
removing GB170 -- all zero
removing GB171 -- all zero
removing GB172 -- all zero
removing GB177 -- all zero
removing GB186 -- all zero
removing GB192 -- all zero
removing GB198 -- all zero
removing GB260 -- all zero
removing GB262 -- all zero
removing GB270 -- all zero
removing GB291 -- all zero
removing GB300 -- all zero
removing GB303 -- all zero
removing GB314 -- all zero
removing GB315 -- all zero
removing GB317 -- all zero
removing GB319 -- all zero
removing GB320 -- all zero
removing GB321 -- all zero
removing GB331 -- all zero
removing GB334 -- all zero
removing GB335 -- all zero
removing GB336 -- all zero
removing GB402 -- all zero
removing GB430 -- all zero
removing TS004 -- all zero
removing TS008 -- all zero
removing TS087 -- all zero
trying URL 'https://raw.githubusercontent.com/NataliiaHue/stability/main/beast/stability_covarion_relaxed.1000.trees'
Content type 'text/plain; charset=utf-8' length 5679476 bytes (5.4 MB)
==================================================
downloaded 5.4 MB

Working on tree 0 
Error in x[[i]] : 
  attempt to select less than one element in integerOneIndex
Calls: add_outgroup_to_tree -> <Anonymous> -> [[ -> [[.multiPhylo
Execution halted
